/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableManager.java
 *
 * Created on 27 sept. 2011, 12:01:45
 */
package isupsimulator.ch.skyguide.isupSimulator.ui.editors.component;

import ch.skyguide.pvss.network.persistency.dpl.DPExportable;
import ch.skyguide.pvss.network.service.Service;
import isupsimulator.ch.skyguide.isupSimulator.ui.editors.Editor;

/**
 *
 * @author caronyn
 */
public class DPManager extends javax.swing.JPanel {

    private DPExportable datasource;
    private Service service;

    /** Creates new form TableManager */
    public DPManager() {
        initComponents();
    }

    // property
    public DPExportable getDatasource() {
        return datasource;
    }

    public void setDatasource(DPExportable datasource) {
        this.datasource = datasource;
    }

    public Service getService() {
        return service;
    }

    public void setService(Service service) {
        this.service = service;
    }
    
    // method
    public void registerEvents(Editor editor) {
        editor.registerLazySpinnerChangedEvent(driverField);
        editor.registerLazyTextChangedEvent(driverNameField);
        editor.registerLazyTextChangedEvent(pollGroupField);
        editor.registerLazySpinnerChangedEvent(agentField);
        editor.registerLazyTextChangedEvent(prefixField);
    }

    public void displayDataModel() {
        driverField.setValue(datasource.getDriverID());
        driverNameField.setText(datasource.getDriverName());
        pollGroupField.setText(datasource.getPollGroup());
        agentField.setValue(datasource.getAgentID());
        prefixField.setText(datasource.getDpPrefix());
    }

    public void storeDataModel() {
        datasource.setDriverID((Integer) driverField.getValue());
        datasource.setDriverName(driverNameField.getText());
        datasource.setPollGroup(pollGroupField.getText());
        datasource.setAgentID((Integer) agentField.getValue());
        datasource.setDpPrefix(prefixField.getText());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        driverField = new javax.swing.JSpinner();
        agentField = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        prefixField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        driverNameField = new javax.swing.JTextField();
        pollGroupField = new javax.swing.JTextField();
        pollGroupLabel = new javax.swing.JLabel();

        jDialog1.setName("jDialog1"); // NOI18N

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(isupsimulator.ISupSimulatorApp.class).getContext().getResourceMap(DPManager.class);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        driverField.setModel(new javax.swing.SpinnerNumberModel(1, 1, 255, 1));
        driverField.setName("driverField"); // NOI18N

        agentField.setModel(new javax.swing.SpinnerNumberModel(1, 1, 400, 1));
        agentField.setName("agentField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        prefixField.setName("prefixField"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        driverNameField.setText(resourceMap.getString("driverNameField.text")); // NOI18N
        driverNameField.setName("driverNameField"); // NOI18N

        pollGroupField.setName("pollGroupField"); // NOI18N

        pollGroupLabel.setText(resourceMap.getString("pollGroupLabel.text")); // NOI18N
        pollGroupLabel.setName("pollGroupLabel"); // NOI18N
        pollGroupLabel.setPreferredSize(new java.awt.Dimension(51, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(driverField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(driverNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agentField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pollGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pollGroupField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prefixField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prefixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(agentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pollGroupField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(pollGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner agentField;
    private javax.swing.JSpinner driverField;
    private javax.swing.JTextField driverNameField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pollGroupField;
    private javax.swing.JLabel pollGroupLabel;
    private javax.swing.JTextField prefixField;
    // End of variables declaration//GEN-END:variables
}
