/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TreeManager.java
 *
 * Created on 24 oct. 2011, 11:52:47
 */
package isupsimulator.ch.skyguide.isupSimulator.ui.editors.component;

import isupsimulator.ch.skyguide.isupSimulator.ui.jtree.JTreeNodeAdapterFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTree;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.jdesktop.application.Action;

/**
 *
 * @author caronyn
 */
public class TreeManager extends javax.swing.JPanel {

    /** Creates new form TreeManager */
    public TreeManager() {
        initComponents();
    }
    private JTree tree;

    public void setTree(JTree tree) {
        this.tree = tree;

        this.tree.addTreeSelectionListener(new TreeSelectionListener() {

            public void valueChanged(TreeSelectionEvent e) {
                tree_selectionChanged(e.getPath());
            }
        });
    }

    // event handle
    private void tree_selectionChanged(TreePath path) {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) path.getLastPathComponent();
        JTreeNodeAdapterFactory factory = JTreeNodeAdapterFactory.valueOf(node.getUserObject());

        addCombo.removeAllItems();

        if (factory.getPossibleChildren() == null) {
            addCombo.setEnabled(false);
            addButton.setEnabled(false);
        } else {
            addCombo.setEnabled(true);
            addButton.setEnabled(true);
            addCombo.setModel(new DefaultComboBoxModel(factory.getPossibleChildren()));
        }
    }

    // action
    @Action
    public void add() {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) tree.getSelectionPath().getLastPathComponent();
        JTreeNodeAdapterFactory nodeFactory = JTreeNodeAdapterFactory.valueOf(node.getUserObject());
        JTreeNodeAdapterFactory newNodeFactory = (JTreeNodeAdapterFactory) addCombo.getSelectedItem();

        Object object = nodeFactory.addChildTo(node.getUserObject(), newNodeFactory);

        DefaultTreeModel model = (DefaultTreeModel) tree.getModel();
        model.insertNodeInto(newNodeFactory.getTreeNodeInstance(object), node, node.getChildCount());
    }

    @Action
    public void remove() {

        for (TreePath path : tree.getSelectionPaths()) {
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) path.getLastPathComponent();
            JTreeNodeAdapterFactory nodeFactory = JTreeNodeAdapterFactory.valueOf(node.getUserObject());

            if (path.getParentPath() != null) {
                DefaultMutableTreeNode parentNode = (DefaultMutableTreeNode) path.getParentPath().getLastPathComponent();
                JTreeNodeAdapterFactory parentNodeFactory = JTreeNodeAdapterFactory.valueOf(parentNode.getUserObject());

                parentNodeFactory.removeChildTo(parentNode.getUserObject(), node.getUserObject());
                DefaultTreeModel model = (DefaultTreeModel) tree.getModel();
                model.removeNodeFromParent(node);
            }
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCombo = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setName("Form"); // NOI18N

        addCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addCombo.setName("addCombo"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(isupsimulator.ISupSimulatorApp.class).getContext().getActionMap(TreeManager.class, this);
        addButton.setAction(actionMap.get("add")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(isupsimulator.ISupSimulatorApp.class).getContext().getResourceMap(TreeManager.class);
        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N

        removeButton.setAction(actionMap.get("remove")); // NOI18N
        removeButton.setText(resourceMap.getString("removeButton.text")); // NOI18N
        removeButton.setName("removeButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeButton)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton)
                    .addComponent(removeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox addCombo;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
