/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LiteralEditor.java
 *
 * Created on Sep 30, 2013, 3:40:49 PM
 */
package isupsimulator.ch.skyguide.isupSimulator.ui.editors;

import ch.skyguide.pvss.network.service.literal.LiteralClient;
import ch.skyguide.pvss.network.service.socket.MessageDelimiter;

/**
 *
 * @author caronyn
 */
public class LiteralEditor extends Editor<LiteralClient> {

    @Override
    public boolean canEdit(Class type) {
        return LiteralClient.class.equals(type);
    }

    @Override
    public void registerEvents() {
        registerLazyTextChangedEvent(nameField);
        registerLazyTextChangedEvent(hostNameField);
        registerLazyTextChangedEvent(hostPortField);
        registerLazyTextChangedEvent(messageField);
        registerLazyComboChangedEvent(delimiterField);
        registerLazyCheckBoxChangedEvent(keepAliveField);
    }

    @Override
    public void displayDataModel() {
        nameField.setText(datasource.getName());
        hostNameField.setText(datasource.getAddress());
        hostPortField.setText(String.valueOf(datasource.getPort()));
        messageField.setText(datasource.getMessage());
        delimiterField.setSelectedItem(datasource.getDelimiter());
        keepAliveField.setSelected(datasource.isKeptAlive());
    }

    @Override
    public void storeDataModel() {
        datasource.setName(nameField.getText());
        datasource.setAddress(hostNameField.getText());
        datasource.setPort(Integer.parseInt(hostPortField.getText()));
        datasource.setMessage(messageField.getText());
        datasource.setDelimiter((MessageDelimiter) delimiterField.getSelectedItem());
        datasource.setKeepAlive(keepAliveField.isSelected());
    }

    /** Creates new form LiteralEditor */
    public LiteralEditor() {
        initComponents();

        for (MessageDelimiter delimiter : MessageDelimiter.values()) {
            delimiterField.addItem(delimiter);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hostNameField = new javax.swing.JTextField();
        hostPortField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sendBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageField = new javax.swing.JTextArea();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        keepAliveField = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        delimiterField = new javax.swing.JComboBox();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(isupsimulator.ISupSimulatorApp.class).getContext().getResourceMap(LiteralEditor.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        hostNameField.setText(resourceMap.getString("hostNameField.text")); // NOI18N
        hostNameField.setName("hostNameField"); // NOI18N

        hostPortField.setName("hostPortField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        sendBtn.setText(resourceMap.getString("sendBtn.text")); // NOI18N
        sendBtn.setName("sendBtn"); // NOI18N
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        messageField.setColumns(20);
        messageField.setRows(5);
        messageField.setName("messageField"); // NOI18N
        jScrollPane1.setViewportView(messageField);

        nameField.setName("nameField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        keepAliveField.setText(resourceMap.getString("keepAliveField.text")); // NOI18N
        keepAliveField.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        keepAliveField.setName("keepAliveField"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        delimiterField.setName("delimiterField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(hostNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(hostPortField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delimiterField, 0, 102, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keepAliveField)
                        .addGap(18, 18, 18)
                        .addComponent(sendBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendBtn)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(hostNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hostPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keepAliveField)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delimiterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed

        datasource.sendMessage();

    }//GEN-LAST:event_sendBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox delimiterCombo;
    private javax.swing.JComboBox delimiterCombo1;
    private javax.swing.JComboBox delimiterField;
    private javax.swing.JTextField hostNameField;
    private javax.swing.JTextField hostPortField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox keepAliveField;
    private javax.swing.JTextArea messageField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
