/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ServiceCompositeEditor.java
 *
 * Created on 14 déc. 2010, 13:32:12
 */

package isupsimulator.ch.skyguide.isupSimulator.ui.editors;

import ch.skyguide.common.event.EventDispatcher;
import ch.skyguide.pvss.network.service.ServiceComposite;
import ch.skyguide.pvss.network.service.snmp.SNMPAgentService;
import isupsimulator.ch.skyguide.isupSimulator.ui.event.DataMVPEvent;
import isupsimulator.ch.skyguide.isupSimulator.ui.event.DataListener;
import org.snmp4j.smi.OctetString;

/**
 *
 * @author caronyn
 */
public class ServiceCompositeEditor extends Editor<ServiceComposite> {

	// methode implementation
	/**
	 * Return if this is the appropriate editor.
	 * @param type Type accepted.
	 * @return Return true if it can edit the type.
	 */
	@Override
	public boolean canEdit(Class type) {
		return ServiceComposite.class.equals(type);
	}

	/**
	 * Register the data change events.
	 */
	@Override
	public void registerEvents() {
		registerLazyTextChangedEvent(nameTextField);
	}

	/**
	 * Data model to view.
	 */
	@Override
	public void displayDataModel() {
		nameTextField.setText(datasource.getName());
	}

	/**
	 * View to Datamodel.
	 */
	@Override
	public void storeDataModel() {
		datasource.setName(nameTextField.getText());
	}

	// constructor
    /** Creates new form ServiceCompositeEditor */
    public ServiceCompositeEditor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(isupsimulator.ISupSimulatorApp.class).getContext().getResourceMap(ServiceCompositeEditor.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        nameTextField.setName("nameTextField"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables

}
