/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SNMPServerEditor.java
 *
 * Created on 14 déc. 2010, 09:39:12
 */
package isupsimulator.ch.skyguide.isupSimulator.ui.editors;

import ch.skyguide.pvss.network.service.xml.ISupSystem;
import ch.skyguide.pvss.network.service.xml.XmlServerService;
import ch.skyguide.pvss.network.service.socket.MessageDelimiter;
import isupsimulator.ch.skyguide.isupSimulator.ui.event.DataMVPEvent;
import isupsimulator.ch.skyguide.isupSimulator.ui.event.DataListener;

/**
 *
 * @author caronyn
 */
public final class XmlServerEditor extends Editor<XmlServerService> {

    @Override
    public void setDataModel(XmlServerService datasource) {
        super.setDataModel(datasource);
        dpManager.setDatasource(datasource);
    }

    // methode implementation
    /**
     * Return if this is the appropriate editor.
     * @param type Type accepted.
     * @return Return true if it can edit the type.
     */
    @Override
    public boolean canEdit(Class type) {
        return XmlServerService.class.equals(type);
    }

    /**
     * Register the data change events.
     */
    @Override
    public void registerEvents() {
        dpManager.registerEvents(this);

        xmlTable.registerEvents();
        xmlTable.AddDataChangedListener(new DataListener<ISupSystem>() {

            public void changed(DataMVPEvent<ISupSystem> event) {
                fireDataChangedEvent();
            }
        });

        registerLazyTextChangedEvent(nameField);
        registerLazyTextChangedEvent(systemNameField);
        registerLazyTextChangedEvent(portField);
        registerLazyTextChangedEvent(heartbeatPeriodField);
        registerLazyTextChangedEvent(statusPeriodField);
        registerLazyComboChangedEvent(delimiterCombo);
    }

    /**
     * Data model to view.
     */
    @Override
    public void displayDataModel() {
        dpManager.displayDataModel();

        xmlTable.setDatasource(datasource.getSystem());
        xmlTable.displayDataModel();

        nameField.setText(datasource.getName());
        systemNameField.setText(datasource.getSystem().getName());
        portField.setText(String.valueOf(datasource.getPort()));
        heartbeatPeriodField.setText(String.valueOf(datasource.getHearbeatPeriod()));
        statusPeriodField.setText(String.valueOf(datasource.getStatusPeriod()));
        delimiterCombo.setSelectedItem(datasource.getDelimiter());
    }

    /**
     * View to Datamodel.
     */
    @Override
    public void storeDataModel() {
        dpManager.storeDataModel();

        datasource.setName(nameField.getText());
        datasource.getSystem().setName(systemNameField.getText());
        datasource.setPort(Integer.valueOf(portField.getText()));
        datasource.setHeartbeatPeriod(Integer.valueOf(heartbeatPeriodField.getText()));
        datasource.setStatusPeriod(Integer.valueOf(statusPeriodField.getText()));
        datasource.setDelimiter((MessageDelimiter) delimiterCombo.getSelectedItem());
    }

    // constructor
    /** Creates new form SNMPServerEditor */
    public XmlServerEditor() {
        initComponents();

        for (MessageDelimiter delimiter : MessageDelimiter.values()) {
            delimiterCombo.addItem(delimiter);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        statusPeriodField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        heartbeatPeriodField = new javax.swing.JTextField();
        xmlTable = new isupsimulator.ch.skyguide.isupSimulator.ui.editors.component.XmlTable();
        jLabel7 = new javax.swing.JLabel();
        systemNameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        delimiterCombo = new javax.swing.JComboBox();
        dpManager = new isupsimulator.ch.skyguide.isupSimulator.ui.editors.component.DPManager();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(isupsimulator.ISupSimulatorApp.class).getContext().getResourceMap(XmlServerEditor.class);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        portField.setName("portField"); // NOI18N

        jLabel3.setName("jLabel3"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        nameField.setName("nameField"); // NOI18N

        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        statusPeriodField.setName("statusPeriodField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        heartbeatPeriodField.setName("heartbeatPeriodField"); // NOI18N

        xmlTable.setName("xmlTable"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        systemNameField.setName("systemNameField"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        delimiterCombo.setName("delimiterCombo"); // NOI18N

        dpManager.setName("dpManager"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(systemNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(portField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(heartbeatPeriodField, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusPeriodField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delimiterCombo, 0, 143, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpManager, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(xmlTable, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel7)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(systemNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(heartbeatPeriodField)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(statusPeriodField))
                        .addGap(2, 2, 2))
                    .addComponent(delimiterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(dpManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xmlTable, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox delimiterCombo;
    private isupsimulator.ch.skyguide.isupSimulator.ui.editors.component.DPManager dpManager;
    private javax.swing.JTextField heartbeatPeriodField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField portField;
    private javax.swing.JTextField statusPeriodField;
    private javax.swing.JTextField systemNameField;
    private isupsimulator.ch.skyguide.isupSimulator.ui.editors.component.XmlTable xmlTable;
    // End of variables declaration//GEN-END:variables
}
